// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuuhiiacdmtgwyjddvzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1dWhpaWFjZG10Z3d5amRkdnpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0ODkyMzUsImV4cCI6MjA3MjA2NTIzNX0.McF6VZrwFxn6CNongkkai-Qzq4uGR-YDbYm6iYjBBFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});